// https://www.geeksforgeeks.org/print-subsequences-string/

/*
Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

Examples:
Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, aa, aaa
*/

#include <bits/stdc++.h>
using namespace std;
using lli = long long int;
using ll = long long;
#define endl '\n'

// Time Complexity : O((2^n) * N) Extra N For Printing, Space Complexity : O(N)
void subsequence(string s, string temp, int index)
{
    if (index == s.size())
    {
        cout << temp << " ,";
        return;
    }

    temp.push_back(s[index]);
    subsequence(s, temp, index + 1);
    temp.pop_back();
    subsequence(s, temp, index + 1);
}

int main()
{
    string s;
    cin >> s;
    subsequence(s, "", 0);

    return 0;
}